package utils

func HandleError(err error) bool {
	//todo
	return true
}
